Repository autoscrape-labs/pydoll, pull requests merged in 2025-03, with the labels that each got.

#30 fix: Get file extension from file path and changes use of reserved word 'format' to 'fmt'
  pydoll/browser/page.py
  pydoll/commands/page.py
  pydoll/element.py
  pydoll/exceptions.py
  tests/test_page_commands.py
Labels: bug

#39 Add tests with many python versions
  .github/workflows/tests.yml
Labels: enhancement

#37 docs: improve documentation for clarity
  pydoll/browser/base.py
  pydoll/browser/chrome.py
  pydoll/browser/managers.py
  pydoll/browser/page.py
  pydoll/commands/dom.py
  pydoll/commands/network.py
  pydoll/commands/runtime.py
  pydoll/commands/storage.py
  pydoll/commands/target.py
  pydoll/connection/connection.py
  pydoll/connection/managers.py
  pydoll/element.py
  pydoll/mixins/find_elements.py
Labels: documentation

#52 Readme improvements
  README.md
Labels: documentation

#63 Handle case where Browser.WindowID is not found and improve error handling.
  pydoll/browser/base.py
  pydoll/browser/page.py
  pydoll/commands/browser.py
  tests/test_browser_window.py
Labels: bug

#47 fix: support multiple default Chrome paths on each OS
  pydoll/browser/chrome.py
  pydoll/browser/managers.py
  tests/test_browser_managers.py
  tests/test_chrome.py
Labels: Review effort 2/5

#78 fix: improve process management and deactivate websockets connection size limit
  pydoll/browser/managers.py
  pydoll/connection/connection.py
Labels: bug, Review effort 2/5

#79 refactor: import commands and evebts from __init__.py
  pydoll/browser/base.py
  pydoll/browser/page.py
  pydoll/commands/__init__.py
  pydoll/element.py
  pydoll/mixins/find_elements.py
  tests/test_browser_commands.py
  tests/test_browser_window.py
  tests/test_chrome.py
  tests/test_dom_commands.py
  tests/test_fetch_commands.py
  tests/test_input_commands.py
  tests/test_network_commands.py
  tests/test_page_commands.py
  tests/test_runtime_commands.py
  tests/test_storage_commands.py
  tests/test_target_commands.py
  tests/test_web_element.py
Labels: Review effort 2/5, refactor

#80 Fix invalid browser events methods
  README.md
  pydoll/browser/base.py
  pydoll/commands/dom.py
  pydoll/events/page.py
  pydoll/exceptions.py
  tests/test_chrome.py
  tests/test_dom_commands.py
  tests/test_events.py
Labels: bug, documentation, Review effort 3/5

#81 Issues and PR templates created
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/refactoring.yml
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/refactoring.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: enhancement, Review effort 2/5

#77 feat: Added support for file uploads.
  pydoll/browser/page.py
  pydoll/commands/dom.py
  pydoll/commands/page.py
  pydoll/element.py
  tests/test_browser_page.py
  tests/test_dom_commands.py
  tests/test_page_commands.py
Labels: Review effort 2/5

#90 Add basic keyboard support to pydoll.
  pydoll/browser/base.py
  pydoll/browser/chrome.py
  pydoll/browser/managers.py
  pydoll/browser/page.py
  pydoll/commands/input.py
  pydoll/common/__init__.py
  pydoll/common/keyboard.py
  pydoll/common/keys.py
  pydoll/connection/connection.py
  pydoll/element.py
  tests/test_browser_managers.py
  tests/test_browser_page.py
  tests/test_browser_window.py
  tests/test_chrome.py
  tests/test_dom_commands.py
  tests/test_exceptions.py
  tests/test_get_special_key.py
  tests/test_input_commands.py
  tests/test_page_commands.py
  tests/test_send_keys.py
  tests/test_send_modifiers_keys.py
  tests/test_web_element.py
Labels: enhancement

#92 Fix：An error is reported when the browser exits
  pydoll/browser/managers.py
  pydoll/connection/connection.py
  tests/test_browser_managers.py
  tests/test_connection_handler.py
Labels: bug
